### ISSUE TITLE
Can't work on macOS.

### ISSUE THREAD

**Issue by fcwork** [magic-akari/ncmc#1] opened 2019-01-16 15:41 UTC
```
total: 1
--------------------------------
   1 <-	test.ncm

thread 'main' panicked at 'slice index starts at 22 but ends at 0', libcore/slice/mod.rs:2340:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
[1]    43069 abort      ncmc
```

**Comment by magic-akari** [comment] 2019-01-16 15:50
Would you like to provide the test.ncm ?

**Comment by fcwork** [comment] 2019-01-17 00:31
分享Eric Clapton的单曲《I Feel Free》http://music.163.com/song/1298758?userid=84189000 (@网易云音乐) SQ quality

**Comment by magic-akari** [comment] 2019-01-17 00:52
cannot reproduce. 
make sure you are using the latest version.

```
➜  ./ncmc "Eric Clapton - I Feel Free.ncm" 
total: 1
--------------------------------
   1 <-	Eric Clapton - I Feel Free.ncm

   musicId	1298758
 musicName	I Feel Free
     album	The Cream of Clapton
    format	flac

  ok ->	Eric Clapton - I Feel Free.flac
--------------------------------
1 success, 0 failed.
```

**Comment by magic-akari** [comment] 2019-01-18 08:38
Any questions? Or can we close this issue?

**Closed** 2019-01-20 04:17 UTC
